# DESAFIO 02
# CRIE UM PROGRAMA QUE LEIA DOIS NÚMEROS E MOSTRE A SOMA ENTRE ELES.

print("Olá! O objetivo é criar um programa que leia dois números e mostre a soma entre eles.")

Primeiro_numero = int(input("Por favor, digite o primeiro número: "))
Segundo_numero  = int(input("Por favor, digite o segundo número: "))

A_soma_dos_numeros = Primeiro_numero + Segundo_numero

print(f"A soma dos números {Primeiro_numero} + {Segundo_numero} resulta no valor de {A_soma_dos_numeros}.")

print("Parabéns, você conseguiu sem consultar o vídeo do Guanabara, porem teve correções a respeito de como usar o int pelo gemine.")