# DESAFIO 09°
# Faça um programa que leia um número inteiro qualquer e mostre na tela a sua tabuada.
 
# Numero digitado = n 

import time

n = int(input("Digite qualquer número para ver sua tabuada: "))
time.sleep(2)

tabuada_01 = (n * 1) 
tabuada_02 = (n * 2)
tabuada_03 = (n * 3)
tabuada_04 = (n * 4)
tabuada_05 = (n * 5)
tabuada_06 = (n * 6)
tabuada_07 = (n * 7)
tabuada_08 = (n * 8)
tabuada_09 = (n * 9)
tabuada_10 = (n * 10)

print("Preparando a Tabuada...")
time.sleep(2) 

print(f"{n} x 01 = {tabuada_01}")
print(f"{n} x 02 = {tabuada_02}")
print(f"{n} x 03 = {tabuada_03}")
print(f"{n} x 04 = {tabuada_04}")
print(f"{n} x 05 = {tabuada_05}")
print(f"{n} x 06 = {tabuada_06}")
print(f"{n} x 07 = {tabuada_07}")
print(f"{n} x 08 = {tabuada_08}")
print(f"{n} x 09 = {tabuada_09}")
print(f"{n} x 10 = {tabuada_10}")
